# Generated by Django 5.1.6 on 2025-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_claim_treatment_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='start_date',
        ),
        migrations.AddField(
            model_name='policy',
            name='additional_information',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
